spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/nutricore_manager}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
app.media.storage-path=${MEDIA_STORAGE_PATH:${user.dir}/storage/editorial-media}
app.security.jwt.secret=${JWT_SECRET:nutricore-dev-jwt-secret-with-32-plus-characters}
app.security.bootstrap.enabled=${APP_SECURITY_BOOTSTRAP_ENABLED:true}
app.security.bootstrap.full-name=${APP_SECURITY_BOOTSTRAP_FULL_NAME:Alberto Vilar}
app.security.bootstrap.email=${APP_SECURITY_BOOTSTRAP_EMAIL:albertovilar1@gmail.com}
app.security.bootstrap.password=${APP_SECURITY_BOOTSTRAP_PASSWORD:132747}
app.security.bootstrap.role=${APP_SECURITY_BOOTSTRAP_ROLE:ADMIN}
