# 1. Configuração de Conexão (H2 em memória)
spring.datasource.url=jdbc:h2:mem:nutricoredb_test;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
# Hibernate apenas valida se a Entidade bate com a Tabela

# 3. Configuração do Flyway para Testes
# Garante que o Flyway limpe o banco antes de rodar os testes, se necessário   
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# 4. Ativação do Console (Opcional em testes, mas útil para debug)
spring.h2.console.enabled=true
app.media.storage-path=${user.dir}/target/test-editorial-media
app.security.jwt.secret=nutricore-test-jwt-secret-with-32-plus-characters
app.security.bootstrap.enabled=true
app.security.bootstrap.full-name=Alberto Vilar
app.security.bootstrap.email=albertovilar1@gmail.com
app.security.bootstrap.password=132747
app.security.bootstrap.role=ADMIN
