package com.nutricore.manager.api.dto;

import java.util.List;

public record PublicProfileResponseDTO(
        Long id,
        String fullName,
        String professionalTitle,
        String professionalSubtitle,
        String biographySummary,
        String heroBadge,
        String heroTitle,
        String heroDescription,
        String heroCardTitle,
        String heroCardDescription,
        String aboutTitle,
        String aboutDescription,
        String aboutImageUrl,
        String primaryCtaLabel,
        String primaryCtaUrl,
        String secondaryCtaLabel,
        String secondaryCtaUrl,
        String contactEmail,
        String contactPhone,
        String whatsappNumber,
        String instagramHandle,
        String linkedinUrl,
        String youtubeUrl,
        String city,
        String officeAddress,
        String heroImageUrl,
        String footerDescription,
        String howItWorksTitle,
        String howItWorksDescription,
        String approachTitle,
        String approachDescription,
        String plansTitle,
        String plansDescription,
        String contactTitle,
        String contactDescription,
        String finalCtaTitle,
        String finalCtaDescription,
        List<PublicSiteMetricItemDTO> siteMetrics,
        List<PublicServicePillarItemDTO> servicePillars,
        List<PublicTestimonialItemDTO> testimonials
) {
}
