CREATE TABLE tb_posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(160) NOT NULL,
    slug VARCHAR(180) NOT NULL,
    summary VARCHAR(500),
    body TEXT NOT NULL,
    cover_image_url VARCHAR(255),
    gallery_image_urls TEXT,
    video_url VARCHAR(255),
    caption VARCHAR(255),
    category VARCHAR(80),
    featured BOOLEAN NOT NULL,
    status VARCHAR(20) NOT NULL,
    published_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,

    CONSTRAINT uk_post_slug UNIQUE (slug)
);

CREATE TABLE tb_articles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(160) NOT NULL,
    slug VARCHAR(180) NOT NULL,
    summary VARCHAR(500) NOT NULL,
    body TEXT NOT NULL,
    cover_image_url VARCHAR(255),
    tags TEXT,
    category VARCHAR(80),
    read_time_minutes INTEGER NOT NULL,
    featured BOOLEAN NOT NULL,
    status VARCHAR(20) NOT NULL,
    published_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,

    CONSTRAINT uk_article_slug UNIQUE (slug)
);

CREATE TABLE tb_recipes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(160) NOT NULL,
    slug VARCHAR(180) NOT NULL,
    description VARCHAR(500) NOT NULL,
    image_url VARCHAR(255),
    ingredients TEXT NOT NULL,
    preparation_steps TEXT NOT NULL,
    prep_time_minutes INTEGER NOT NULL,
    yield_info VARCHAR(80) NOT NULL,
    category VARCHAR(80),
    featured BOOLEAN NOT NULL,
    status VARCHAR(20) NOT NULL,
    published_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,

    CONSTRAINT uk_recipe_slug UNIQUE (slug)
);
