CREATE TABLE patients (

    -- Usando BIGINT para casar com o Long do Java
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    name VARCHAR(100) NOT NULL,
    email VARCHAR(150) NOT NULL,
    phone VARCHAR(20) NOT NULL,
    birth_date DATE NOT NULL,
    gender VARCHAR(20) NOT NULL,
    occupation VARCHAR(100),
    life_style VARCHAR(30) NOT NULL,
    status VARCHAR(20) NOT NULL,

    -- O Spring Auditing preenche estes campos
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,

    -- Nomeamos a restrição para ser mais profissional
    CONSTRAINT uk_patient_email UNIQUE (email)
);