CREATE TABLE tb_clinical_anamnesis (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    clinical_history TEXT,
    family_history TEXT,
    medication_use TEXT,
    sleep_quality VARCHAR(20) NOT NULL,
    bowel_function VARCHAR(20) NOT NULL,

    water_intake_goal FLOAT,
    date DATE NOT NULL,
    patient_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL,

    CONSTRAINT fk_anamnesis_patient FOREIGN KEY (patient_id) REFERENCES tb_patients (id)
);

CREATE INDEX idx_anamnesis_patient_id ON tb_clinical_anamnesis(patient_id);