CREATE TABLE tb_public_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(120) NOT NULL,
    professional_title VARCHAR(120) NOT NULL,
    hero_badge VARCHAR(180) NOT NULL,
    hero_title VARCHAR(180) NOT NULL,
    hero_description VARCHAR(500) NOT NULL,
    about_title VARCHAR(120) NOT NULL,
    about_description TEXT NOT NULL,
    primary_cta_label VARCHAR(80) NOT NULL,
    primary_cta_url VARCHAR(255) NOT NULL,
    secondary_cta_label VARCHAR(80) NOT NULL,
    secondary_cta_url VARCHAR(255) NOT NULL,
    contact_email VARCHAR(150) NOT NULL,
    contact_phone VARCHAR(20) NOT NULL,
    instagram_handle VARCHAR(80) NOT NULL,
    city VARCHAR(80) NOT NULL,
    hero_image_url VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP
);

CREATE TABLE tb_public_plans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(80) NOT NULL,
    subtitle VARCHAR(120) NOT NULL,
    price_label VARCHAR(40) NOT NULL,
    summary VARCHAR(500) NOT NULL,
    features TEXT NOT NULL,
    featured BOOLEAN NOT NULL,
    cta_label VARCHAR(80) NOT NULL,
    display_order INTEGER NOT NULL
);

CREATE TABLE tb_public_posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(140) NOT NULL,
    slug VARCHAR(140) NOT NULL,
    category VARCHAR(80) NOT NULL,
    excerpt VARCHAR(500) NOT NULL,
    read_time_minutes INTEGER NOT NULL,
    image_url VARCHAR(255) NOT NULL,
    published_at DATE NOT NULL,

    CONSTRAINT uk_public_post_slug UNIQUE (slug)
);

CREATE TABLE tb_public_recipes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(140) NOT NULL,
    slug VARCHAR(140) NOT NULL,
    summary VARCHAR(500) NOT NULL,
    image_url VARCHAR(255) NOT NULL,
    prep_time_minutes INTEGER NOT NULL,
    calories_label VARCHAR(40) NOT NULL,
    ingredients TEXT NOT NULL,
    preparation_steps TEXT NOT NULL,
    display_order INTEGER NOT NULL,

    CONSTRAINT uk_public_recipe_slug UNIQUE (slug)
);
